apiVersion: v1
kind: Service
metadata:
  name: tawazun-serv
spec:
 selector:
   app: tawazun-web
   name: adwaa-web
 type: NodePort
 ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31040